#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

iptables -L -n -v | grep -q $1
RETVAL=$?

if [ $RETVAL -eq 0 ]; then

        echo "IP address already in blocklist: $1"
        exit 0

fi
echo  "${NC}[${GREEN}+${NC}] ${GREEN}Adding enemy${NC} $1";
iptables -A Enemies -s $1 -j DROP
